#!/bin/sh
#
# bootstrap
#
# Prepare hubot development environment.

set -e

#
# Welcome to Hubot
#
echo ""
echo "      __          __          __   "
echo "     / /_  __  __/ /_  ____  / /_  "
echo "    / __ \/ / / / __ \/ __ \/ __/  "
echo "   / / / / /_/ / /_/ / /_/ / /_    "
echo "  /_/ /_/\__,_/_.___/\____/\__/    "
echo ""
echo "  The Robot For You."
echo ""

#
# Check for Homebrew
# 
if test ! $(which brew)
then
  echo "  x You need to install Homebrew:"
  echo "    ruby -e '\$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)'"
  exit 1
else
  echo "  + Homebrew found."
fi

#
# Install Node.js
#
if test ! $(which node)
then
  echo "  + Installing node.js."
  brew install node.js
else
  echo "  + Node.js found."
fi

#
# Install Redis
#
if test ! $(which redis-server)
then
  echo "  + Installing redis."
  brew install redis
else
  echo "  + Redis found."
fi

#
# Install hubot and coffee-script npm
# 
if test ! $(which hubot) || test ! $(which coffee)
then
  echo "  + Installing hubot and coffee-script."
  npm install -g hubot coffee-script
else
  echo "  + hubot and coffee found."
fi

#
# Create Config
#
if test -f ".env"
then
  echo "  + Config file found."
else
  echo "  + Creating config file."
  echo "    If you'd like to configure your hubot, modify '.env'"
  cp .env.sample .env
fi

#
# Startup Instructions
#
echo ""

echo "  Good work. We're ready."
echo "  Run 'script/start' to start your hubot."

exit 0
