#!/bin/sh
#
# start
#
# Starting script
#
# Usage:
#   start         - starting hubot with shell adapter
#   start hipchat - starting hubot with hipchat adapter

#
# Check npm dependencies.
#
echo "  + Checking npms."
npm install

#
# Load environment variables.
#
echo "  + Loading environment varibales."
for line in `cat .env`
do
  if [[ ${line} =~ ^# ]] || [ -z "${line}" ]
  then
    continue
  else
    export ${line}
  fi
done

#
# Start a hubot instance
#
echo "  + Starting your hubot."
if test $# -eq 1
then
  bin/hubot -a $1
else
  bin/hubot
fi
